

const fakeCampGroundData = {
  "METADATA": {
      "RESULTS": {
          "CURRENT_COUNT": 5,
          "TOTAL_COUNT": 44
      },
      "SEARCH_PARAMETERS": {
          "LIMIT": 5,
          "OFFSET": 0,
          "QUERY": ""
      }
  },
  "RECDATA": [
      {
          "ACTIVITY": [],
          "CAMPSITE": [],
          "EVENT": [],
          "Enabled": true,
          "FACILITYADDRESS": [],
          "FacilityAdaAccess": "",
          "FacilityDescription": "The Ogden Museum of Southern Art represents a full range of art recounting the history and changing aesthetics of painting in Louisiana. The museum offers the visitor an experience of the South's past and present with 18th, 19th, 20th and 21st century works in print, ceramic, photograph and sculpture, in addition to paintings.",
          "FacilityDirections": "",
          "FacilityEmail": "",
          "FacilityID": "203226",
          "FacilityLatitude": 29.9544,
          "FacilityLongitude": -90.075,
          "FacilityMapURL": "",
          "FacilityName": "Ogden Museum of Southern Art",
          "FacilityPhone": "",
          "FacilityReservationURL": "",
          "FacilityTypeDescription": "Facility",
          "FacilityUseFeeDescription": "",
          "GEOJSON": {
              "COORDINATES": [
                  -90.075,
                  29.9544
              ],
              "TYPE": "Point"
          },
          "Keywords": "",
          "LINK": [],
          "LastUpdatedDate": "2020-09-10",
          "LegacyFacilityID": "SIAP",
          "MEDIA": [
              {
                  "Credits": "",
                  "Description": "",
                  "EmbedCode": "",
                  "EntityID": "203226",
                  "EntityMediaID": "200",
                  "EntityType": "Facility",
                  "Height": 0,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "",
                  "URL": "https://cdn.recreation.gov/public/images/200.jpg",
                  "Width": 0
              }
          ],
          "ORGANIZATION": [],
          "OrgFacilityID": "",
          "PERMITENTRANCE": [],
          "ParentOrgID": "138",
          "ParentRecAreaID": "",
          "RECAREA": [],
          "Reservable": false,
          "StayLimit": "",
          "TOUR": []
      },
      {
          "ACTIVITY": [],
          "CAMPSITE": [],
          "EVENT": [],
          "Enabled": true,
          "FACILITYADDRESS": [],
          "FacilityAdaAccess": "",
          "FacilityDescription": "The Natchitoches National Fish Hatchery became operational in 1931 under the authority of the White Act as a warm water facility that would produce catfish, largemouth bass, bluegill, and redear sunfish for local public waters and farm ponds. Since 1931, resource needs in the southeast have changed and the mission of the station has changed with the times. Recovery of threatened or endangered species (Louisiana pearlshell mussel), restoration of imperiled species (alligator snapping turtle, paddlefish) and management of interjurisdictional fisheries are also raised to accommodate recreational fishing needs and restoration efforts on Service Lands. There are 53 ponds, each averaging 0.8 acres in size.",
          "FacilityDirections": "Exit I-49 at Exit 138 and take Highway 6 East until it intersects with LA 3110 (this should be the first traffic light). Take a right onto LA 3110 and follow it until it dead ends into LA 1. Take a left on to LA 1. The hatchery will be on the right approximately one half mile. You will see a long hurricane fence that encloses the ponds and hatchery property and then the Natchitoches National Fish Hatchery sign in front of the public aquarium building.",
          "FacilityEmail": "brett_hortman@fws.gov",
          "FacilityID": "203875",
          "FacilityLatitude": 31.74200058,
          "FacilityLongitude": -93.11450195,
          "FacilityMapURL": "",
          "FacilityName": "Natchitoches National Fish Hatchery",
          "FacilityPhone": "(318) 352-5324",
          "FacilityReservationURL": "",
          "FacilityTypeDescription": "Facility",
          "FacilityUseFeeDescription": "",
          "GEOJSON": {
              "COORDINATES": [
                  -93.11450195,
                  31.74200058
              ],
              "TYPE": "Point"
          },
          "Keywords": "National Fish Hatchery, Hatchery, US Fish and Wildlife Service, fisheries, Fish and Aquatic Conservation",
          "LINK": [],
          "LastUpdatedDate": "2020-12-09",
          "LegacyFacilityID": "FWS",
          "MEDIA": [],
          "ORGANIZATION": [],
          "OrgFacilityID": "",
          "PERMITENTRANCE": [],
          "ParentOrgID": "127",
          "ParentRecAreaID": "70906",
          "RECAREA": [],
          "Reservable": false,
          "StayLimit": "",
          "TOUR": []
      },
      {
          "ACTIVITY": [],
          "CAMPSITE": [],
          "EVENT": [],
          "Enabled": true,
          "FACILITYADDRESS": [],
          "FacilityAdaAccess": "N",
          "FacilityDescription": "<h2>Overview</h2>\nBeaver Dam Campground is situated on the shores of Upper Caney Lake in the Caney Lakes Recreation Complex. The campground is located in a beautiful setting among woods, lakes and hills. Swimming, boating, fishing and water skiing are the top activities.  \n<br/><br/>\nSugar Cane National Recreation Trail passes right next to the campground and offers varied terrain for hikers and bikers. The Sugar Cane trail was named for the crop that was once cultivated here, in addition to cotton. \n<h2>Recreation</h2>\nBass, crappie, catfish, bluegill and sandbass can be caught in the lakes. The Sugar Cane Trail spans 5.7 miles and the Lost Man Loop spans 2 miles. Both are open to hiking and mountain biking. <h2>Facilities</h2>\nCampsites come with electric and water hookups. The group picnic area accommodates up to 200 guests while each campsite fits up to eight campers. A sanitary dump station, drinking water and flush toilets are provided. <h2>Natural Features</h2>\nBeaver Dam sits at an elevation of 160 feet along the north shores of the 125-acre Upper Caney Lake. The group picnic area is near Lower Caney Lake, spanning 250 acres. <br/><br/>\nKisatchie National Forest, the only national forest in Louisiana, spans 604,000 acres and mostly consists of bayous with bald cypress groves and old growth pine.\n<h2>Nearby Attractions</h2>\nThe city of Minden has restaurants, shopping and golfing. \n",
          "FacilityDirections": "From Minden, take Louisiana 159 north to Caney Lake Road (Webster Parish Road 111) . Turn left on Caney lake Road, continue 2 miles to recreation area entrance. ",
          "FacilityEmail": "",
          "FacilityID": "233319",
          "FacilityLatitude": 32.6736111,
          "FacilityLongitude": -93.3055556,
          "FacilityMapURL": "",
          "FacilityName": "Beaver Dam Campground (Kisatchie National Forest, LA)",
          "FacilityPhone": "318-927-2061",
          "FacilityReservationURL": "",
          "FacilityTypeDescription": "Campground",
          "FacilityUseFeeDescription": "",
          "GEOJSON": {
              "COORDINATES": [
                  -93.3055556,
                  32.6736111
              ],
              "TYPE": "Point"
          },
          "Keywords": "CANEY LAKES RECREATION AREA,KISATCHIE NATIONAL FOREST,Beaver Dam,Caney Lakes",
          "LINK": [],
          "LastUpdatedDate": "2023-03-28",
          "LegacyFacilityID": "72341",
          "MEDIA": [
              {
                  "Credits": "",
                  "Description": "",
                  "EmbedCode": "",
                  "EntityID": "233319",
                  "EntityMediaID": "2575740",
                  "EntityType": "Facility",
                  "Height": 360,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "BEAVER DAM CAMPGROUND",
                  "URL": "https://cdn.recreation.gov/public/images/68883.jpg",
                  "Width": 540
              },
              {
                  "Credits": "",
                  "Description": "",
                  "EmbedCode": "",
                  "EntityID": "233319",
                  "EntityMediaID": "2575846",
                  "EntityType": "Facility",
                  "Height": 360,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "BEAVER DAM CAMPGROUND",
                  "URL": "https://cdn.recreation.gov/public/images/69007.jpg",
                  "Width": 540
              },
              {
                  "Credits": "",
                  "Description": "",
                  "EmbedCode": "",
                  "EntityID": "233319",
                  "EntityMediaID": "2575872",
                  "EntityType": "Facility",
                  "Height": 360,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "BEAVER DAM CAMPGROUND",
                  "URL": "https://cdn.recreation.gov/public/images/69036.jpg",
                  "Width": 540
              },
              {
                  "Credits": "",
                  "Description": "",
                  "EmbedCode": "",
                  "EntityID": "233319",
                  "EntityMediaID": "074d5766-4dd9-4796-8414-e80be259fc70",
                  "EntityType": "Facility",
                  "Height": 360,
                  "IsGallery": false,
                  "IsPreview": false,
                  "IsPrimary": true,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "BEAVER DAM CAMPGROUND",
                  "URL": "https://cdn.recreation.gov/public/2019/03/08/23/34/233319_3faa2c98-ee24-4f88-8258-763d3a3a7633.jpg",
                  "Width": 540
              },
              {
                  "Credits": "",
                  "Description": "",
                  "EmbedCode": "",
                  "EntityID": "233319",
                  "EntityMediaID": "2575891",
                  "EntityType": "Facility",
                  "Height": 360,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "BEAVER DAM CAMPGROUND",
                  "URL": "https://cdn.recreation.gov/public/images/69059.jpg",
                  "Width": 540
              },
              {
                  "Credits": "",
                  "Description": "",
                  "EmbedCode": "",
                  "EntityID": "233319",
                  "EntityMediaID": "2575780",
                  "EntityType": "Facility",
                  "Height": 360,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "BEAVER DAM CAMPGROUND",
                  "URL": "https://cdn.recreation.gov/public/images/68928.jpg",
                  "Width": 540
              },
              {
                  "Credits": "",
                  "Description": "",
                  "EmbedCode": "",
                  "EntityID": "233319",
                  "EntityMediaID": "2575879",
                  "EntityType": "Facility",
                  "Height": 360,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "BEAVER DAM CAMPGROUND",
                  "URL": "https://cdn.recreation.gov/public/images/69045.jpg",
                  "Width": 540
              }
          ],
          "ORGANIZATION": [],
          "OrgFacilityID": "AN372341",
          "PERMITENTRANCE": [],
          "ParentOrgID": "131",
          "ParentRecAreaID": "1043",
          "RECAREA": [],
          "Reservable": true,
          "StayLimit": "",
          "TOUR": []
      },
      {
          "ACTIVITY": [],
          "CAMPSITE": [],
          "EVENT": [],
          "Enabled": true,
          "FACILITYADDRESS": [],
          "FacilityAdaAccess": "",
          "FacilityDescription": "<p>The Hilton Baton Rouge Capitol Center, built in 1927 and a member of Historic Hotels of America® since 2015 was listed in the National Register of Historic Places in 1982. </p>\n<p>Historic Hotels of America is the official program of the National Trust for Historic Preservation® for recognizing and celebrating the finest historic hotels across America.</p>\n<p>The Hilton Capitol Center once again stands proud as it did when it was originally constructed in 1927 and called home by Huey Long. In a state where every man is a king and in a building where the past becomes the present, the hotel blends both history and elegance. The historic Heidelberg and Capitol House Hotel have been fully restored to their former state of grandeur with over $70 million in renovations. Overlooking the beautiful Mississippi River and located in picturesque downtown Baton Rouge, the hotel is adjacent to the Shaw Center and the River Center Convention Center. It is also less than five minutes from the Louisiana State Capitol and three miles from Louisiana State University. </p>\n\n<p>For Price Match Guarantee and Special Offers please visit, please visit <a href=\"http://www.historichotels.org/hotels-resorts/hilton-baton-rouge-capitol-center/\" rel=\"nofollow\">HistoricHotels.org</a>.  </p>\n",
          "FacilityDirections": "<p>The hotel is located at 201 Lafayette Street in the heart of downtown Baton Rouge. Easily accessible from I-110 North via North Street or I-110 South via Laurel. Baton Rouge Metropolitan Airport: 8 miles, 15 minutes. New Orleans Int'l Airport: 75 miles, 1 hour. </p>\n\n<p>Visit HistoricHotels.org to <a href=\"http://www.historichotels.org/hotels-resorts/hilton-baton-rouge-capitol-center/\" rel=\"nofollow\">get \n  more information</a>, <a href=\"http://www.historichotels.org/hotels-resorts/hilton-baton-rouge-capitol-center/hotel-deals.php\" rel=\"nofollow\">view special offers</a> or <a href=\"https://www.reservations-page.com/c00550/h11866/be_hha.aspx?psk801=teaserbox&__iata=00015506&adults=1&lg=en&cmd=post&src=180510192&_ga=1.224191835.1548406949.1411503776\" rel=\"nofollow\">make a reservation</a>. Save up to 50% off best available rates at participating historic hotels with a free membership to the National Trust for Historic Preservation.</p>",
          "FacilityEmail": "info@historichotels.org",
          "FacilityID": "234797",
          "FacilityLatitude": 30.44,
          "FacilityLongitude": -91.19,
          "FacilityMapURL": "",
          "FacilityName": "Hilton Baton Rouge Capitol Center",
          "FacilityPhone": "+1 800 678 8946",
          "FacilityReservationURL": "",
          "FacilityTypeDescription": "Facility",
          "FacilityUseFeeDescription": "",
          "GEOJSON": {
              "COORDINATES": [
                  -91.19,
                  30.44
              ],
              "TYPE": "Point"
          },
          "Keywords": "",
          "LINK": [],
          "LastUpdatedDate": "2020-09-10",
          "LegacyFacilityID": "",
          "MEDIA": [
              {
                  "Credits": "",
                  "Description": "Take a break during a busy convention or bustling vacation to enjoy the activities on-site including an outdoor swimming pool.",
                  "EmbedCode": "",
                  "EntityID": "234797",
                  "EntityMediaID": "95106",
                  "EntityType": "Facility",
                  "Height": 885,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "Oasis in the City",
                  "URL": "https://cdn.recreation.gov/public/2019/07/30/19/03/234797_3f8dcd0f-1735-4ed7-8044-a7190a3581ed_1440.jpeg",
                  "Width": 1440
              },
              {
                  "Credits": "",
                  "Description": "With convenient shuttles to area casinos and airports, as well as walking distance to the Shaw Center and the River Center Convention Center, the hotel's location is perfect for everyone.",
                  "EmbedCode": "",
                  "EntityID": "234797",
                  "EntityMediaID": "2720",
                  "EntityType": "Facility",
                  "Height": 885,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "Surrounded by Baton Rouge",
                  "URL": "https://cdn.recreation.gov/public/2019/07/30/19/03/234797_ab3c2d21-937e-423a-b19b-dd5ab3352d7d_1440.jpeg",
                  "Width": 1440
              },
              {
                  "Credits": "",
                  "Description": "The Riverview Ballroom is one of several meeting spaces available. Spaces can accommodate up to 800 guests.",
                  "EmbedCode": "",
                  "EntityID": "234797",
                  "EntityMediaID": "95108",
                  "EntityType": "Facility",
                  "Height": 885,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "Riverview Ballroom",
                  "URL": "https://cdn.recreation.gov/public/2019/07/30/19/03/234797_341704e8-b051-4c56-b784-1576245c21b7_1440.jpeg",
                  "Width": 1440
              },
              {
                  "Credits": "",
                  "Description": "The history of this hotel cannot be recounted with mentioning the infamous governor Huey Long. Not only was Long a guest and frequent visitor of the hotel, he also faced an opposition government that ran their administration out of the then Hiedelberg Hotel.",
                  "EmbedCode": "",
                  "EntityID": "234797",
                  "EntityMediaID": "93725",
                  "EntityType": "Facility",
                  "Height": 885,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "An Infamous History ",
                  "URL": "https://cdn.recreation.gov/public/2019/07/30/19/03/234797_126e07ec-c86a-42a6-aa3e-6cb9bf1fbad2_1440.jpeg",
                  "Width": 1440
              },
              {
                  "Credits": "",
                  "Description": "",
                  "EmbedCode": "",
                  "EntityID": "234797",
                  "EntityMediaID": "95105",
                  "EntityType": "Facility",
                  "Height": 945,
                  "IsGallery": false,
                  "IsPreview": false,
                  "IsPrimary": true,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "Hilton Baton Rouge Capitol Center",
                  "URL": "https://cdn.recreation.gov/public/2019/07/30/19/03/234797_7f26618c-5b38-4c46-811d-0d329e5c17b8_1440.jpeg",
                  "Width": 1440
              },
              {
                  "Credits": "",
                  "Description": "The Hilton Capitol Center has an extensive Art Collection. Guests can enjoy a self guided art tour through the hallway and corridors of the hotel or even take history home with some of the pieces available for sale.",
                  "EmbedCode": "",
                  "EntityID": "234797",
                  "EntityMediaID": "95107",
                  "EntityType": "Facility",
                  "Height": 885,
                  "IsGallery": true,
                  "IsPreview": false,
                  "IsPrimary": false,
                  "MediaType": "Image",
                  "Subtitle": "",
                  "Title": "An Artistic Experience ",
                  "URL": "https://cdn.recreation.gov/public/2019/07/30/19/03/234797_82d9de7b-d858-41d0-a804-9ae034cef5e8_1440.jpeg",
                  "Width": 1440
              }
          ],
          "ORGANIZATION": [],
          "OrgFacilityID": "",
          "PERMITENTRANCE": [],
          "ParentOrgID": "143",
          "ParentRecAreaID": "",
          "RECAREA": [],
          "Reservable": false,
          "StayLimit": "",
          "TOUR": []
      },
      {
          "ACTIVITY": [],
          "CAMPSITE": [],
          "EVENT": [],
          "Enabled": true,
          "FACILITYADDRESS": [],
          "FacilityAdaAccess": "",
          "FacilityDescription": "Catahoula National Wildlife Management Preserve (NWMP)1",
          "FacilityDirections": "",
          "FacilityEmail": "",
          "FacilityID": "240845",
          "FacilityLatitude": 0,
          "FacilityLongitude": 0,
          "FacilityMapURL": "",
          "FacilityName": "Catahoula National Wildlife Management Preserve (NWMP)1",
          "FacilityPhone": "",
          "FacilityReservationURL": "",
          "FacilityTypeDescription": "Facility",
          "FacilityUseFeeDescription": "",
          "GEOJSON": {
              "COORDINATES": null,
              "TYPE": ""
          },
          "Keywords": "",
          "LINK": [],
          "LastUpdatedDate": "2020-09-10",
          "LegacyFacilityID": "",
          "MEDIA": [],
          "ORGANIZATION": [],
          "OrgFacilityID": "34853",
          "PERMITENTRANCE": [],
          "ParentOrgID": "131",
          "ParentRecAreaID": "1043",
          "RECAREA": [],
          "Reservable": false,
          "StayLimit": "",
          "TOUR": []
      }
  ]
}

module.exports = fakeCampGroundData